Repository 1908-aug19-java/Project2-Samuel-Chris-Kyle-BackEnd, pull requests merged in 2019-09, with the labels that each got.

#11 Reconfigured properties file and added Custom config file
  gamesgalore/src/main/java/com/revature/gamesgalore/CustomConfig.java
  gamesgalore/src/main/resources/application.properties
Labels: bug

#12 Pushing Issue #9 Resolution to Master
  gamesgalore/src/main/java/com/revature/gamesgalore/CustomConfig.java
  gamesgalore/src/main/resources/application.properties
Labels: bug

#14 Update README enhancement issue #13
  README.md
Labels: enhancement

#15 Updating Master with Proper Markdown Documentation
  README.md
Labels: documentation

#16 Removed CustomConfig class and application.properties.
  gamesgalore/src/main/java/com/revature/gamesgalore/CustomConfig.java
  gamesgalore/src/main/java/com/revature/gamesgalore/GamesgaloreApplication.java
  gamesgalore/src/main/resources/application.properties
Labels: bug

#23 Added try catch to userdetails service for exception on jenkins
  gamesgalore/src/main/java/com/revature/gamesgalore/springimpl/AccountDetailsService.java
Labels: enhancement
